while(1)
    stri=input('Enter Morse Code Character','s');
na=((strcmp(stri,'a'))||(strcmp(stri,'A')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\A.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'b'))||(strcmp(stri,'B')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\B.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'c'))||(strcmp(stri,'C')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\C.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'d'))||(strcmp(stri,'D')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\D.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'e'))||(strcmp(stri,'E')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\E.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'f'))||(strcmp(stri,'F')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\F.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'g'))||(strcmp(stri,'G')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\G.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'h'))||(strcmp(stri,'H')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\H.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'i'))||(strcmp(stri,'I')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\I.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'j'))||(strcmp(stri,'J')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\J.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'k'))||(strcmp(stri,'K')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\K.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'l'))||(strcmp(stri,'L')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\L.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'m'))||(strcmp(stri,'M')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\M.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'n'))||(strcmp(stri,'N')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\N.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'o'))||(strcmp(stri,'O')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\O.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'p'))||(strcmp(stri,'P')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\P.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'q'))||(strcmp(stri,'Q')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\Q.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'r'))||(strcmp(stri,'R')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\R.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'s'))||(strcmp(stri,'S')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\S.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'t'))||(strcmp(stri,'T')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\T.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'u'))||(strcmp(stri,'U')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\U.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'v'))||(strcmp(stri,'V')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\V.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'w'))||(strcmp(stri,'W')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\W.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'x'))||(strcmp(stri,'X')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\X.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'y'))||(strcmp(stri,'Y')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\Y.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'z'))||(strcmp(stri,'Z')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\Z.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'0')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\0.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'1')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\1.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'2')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\2.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'3')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\3.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'4')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\4.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'5')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\5.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'6')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\6.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'7')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\7.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'8')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\8.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'9')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\9.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'.')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\dot.jpg')
    pause(2);
    close
end
na=((strcmp(stri,',')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\comma.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'?')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\qm.jpg')
    pause(2);
    close
end
na=((strcmp(stri,'!')));
if(na==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\em.jpg')
    pause(2);
    close
end
end