clc;
clear;
close all;
a=['.-'];
b=['-...'];
c=['-.-.'];
d=['-...'];
e=['.'];
f=['..-.'];
g=['--.'];
h=['....'];
i=['..'];
j=['.---'];
k=['-.-'];
l=['.-..'];
m=['--'];
n=['-.'];
o=['---'];
p=['.--.'];
q=['--.-'];
r=['.-.'];
s=['...'];
t=['-'];
u=['..-'];
v=['...-'];
w=['-..-'];
x=['-..-'];
y=['-.--'];
z=['--..'];
zero=['-----'];
one=['.----'];
two=['..---'];
three=['...--'];
four=['....-'];
five=['.....'];
six=['-....'];
seven=['--...'];
eight=['---..'];
nine=['----.'];
dot=['.-.-.-'];
comma=['--.--'];
qm=['..--..'];
em=['-.-.--'];
%str=inputdlg('Enter Morse Code Character','s');
ma=(strcmp(str,a));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\A.jpg')
    pause(2);
    close
end
ma=(strcmp(str,b));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\B.jpg')
    pause(2);
    close
end
ma=(strcmp(str,c));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\C.jpg')
    pause(2);
    close
end
ma=(strcmp(str,d));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\D.jpg')
    pause(2);
    close
end
ma=(strcmp(str,e));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\E.jpg')
    pause(2);
    close
end
ma=(strcmp(str,f));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\F.jpg')
    pause(2);
    close
end
ma=(strcmp(str,g));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\G.jpg')
    pause(2);
    close
end
ma=(strcmp(str,h));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\H.jpg')
    pause(2);
    close
end
ma=(strcmp(str,i));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\I.jpg')
    pause(2);
    close
end
ma=(strcmp(str,j));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\J.jpg')
    pause(2);
    close
end
ma=(strcmp(str,k));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\K.jpg')
    pause(2);
    close
end
ma=(strcmp(str,l));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\L.jpg')
    pause(2);
    close
end
ma=(strcmp(str,m));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\M.jpg')
    pause(2);
    close
end
ma=(strcmp(str,n));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\N.jpg')
    pause(2);
    close
end
ma=(strcmp(str,o));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\O.jpg')
    pause(2);
    close
end
ma=(strcmp(str,p));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\P.jpg')
    pause(2);
    close
end
ma=(strcmp(str,q));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\Q.jpg')
    pause(2);
    close
end
ma=(strcmp(str,r));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\R.jpg')
    pause(2);
    close
end
ma=(strcmp(str,s));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\S.jpg')
    pause(2);
    close
end
ma=(strcmp(str,t));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\T.jpg')
    pause(2);
    close
end
ma=(strcmp(str,u));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\U.jpg')
    pause(2);
    close
end
ma=(strcmp(str,v));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\V.jpg')
    pause(2);
    close
end
ma=(strcmp(str,w));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\W.jpg')
    pause(2);
    close
end
ma=(strcmp(str,x));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\X.jpg')
    pause(2);
    close
end
ma=(strcmp(str,y));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\Y.jpg')
    pause(2);
    close
end
ma=(strcmp(str,z));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\Z.jpg')
    pause(2);
    close
end
ma=(strcmp(str,zero));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\0.jpg')
    pause(2);
    close
end
ma=(strcmp(str,one));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\1.jpg')
    pause(2);
    close
end
ma=(strcmp(str,two));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\2.jpg')
    pause(2);
    close
end
ma=(strcmp(str,three));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\3.jpg')
    pause(2);
    close
end
ma=(strcmp(str,four));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\4.jpg')
    pause(2);
    close
end
ma=(strcmp(str,five));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\5.jpg')
    pause(2);
    close
end
ma=(strcmp(str,six));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\6.jpg')
    pause(2);
    close
end
ma=(strcmp(str,seven));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\7.jpg')
    pause(2);
    close
end
ma=(strcmp(str,eight));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\8.jpg')
    pause(2);
    close
end
ma=(strcmp(str,nine));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\9.jpg')
    pause(2);
    close
end
ma=(strcmp(str,dot));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\dot.jpg')
    pause(2);
    close
end
ma=(strcmp(str,comma));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\comma.jpg')
    pause(2);
    close
end
ma=(strcmp(str,qm));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\qm.jpg')
    pause(2);
    close
end
ma=(strcmp(str,em));
if(ma==1)
    imshow('E:\\aidifico\\PROJECT\\letters\\em.jpg')
    pause(2);
    close
end
